# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=87771cdd6d
# ROOST_METHOD_SIG_HASH=0a68a12aee
# 
#  ########## Scenario ########## 
# 
# {
#   background: 'Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: 'Delete authorization\r\n' +
#     '    Given authorization ID\r\n' +
#     '    When the client sends a DELETE request to "/authorizations/ID"\r\n' +
#     '    Then the response status code should be 200 for a successful delete\r\n' +
#     '    And the authorizations should not appear in GET request for "/authorizations"',
#   title: 'Delete authorization'
# }
# 

# ********RoostGPT********
Feature: Delete Authorization

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authId = '123e4567-e89b-12d3-a456-426614174000' # Example UUID for authorization ID
    * def Token = 'example-token' # Example API Token for authorization
  
  @delete
  Scenario: Delete an existing authorization and verify it no longer exists
    # Delete the authorization with a specific ID
    Given path 'authorizations', authId
    And header Token = Token
    When method delete
    Then status 200
    And assert responseHeaders['api-version'] == '1.0.0'
    # Comment: The above steps test the DELETE method for an authorization ID and expects a 200 status for successful deletion.

    # Verify the authorization with the specific ID has been deleted
    Given path 'authorizations'
    And header Token = Token
    When method get
    Then status 200
    And assert responseHeaders['api-version'] == '1.0.0'
    And def jsonResponse = response
    And assert !jsonResponse.authorizations.some(auth => auth.id == authId)
    # Comment: The above steps verify that the deleted authorization does not appear in the GET request for "/authorizations".
