# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /accounts_patch for http method type PATCH 
# RoostTestHash=2758affb7e
# 
# 

# ********RoostGPT********
Feature: Login to existing Account

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = authToken

  Scenario Outline: Successful login to an account with valid email
    Given path '/accounts'
    And request
      """
      { email: '<email>' }
      """
    When method post
    Then status 200
    And match header api-version == '1.0.0'
    And match response == { id: '#notnull', email: '<email>', status: 'active' }

    Examples:
      | read('accounts_patch.csv') |

  Scenario Outline: Attempt login with invalid email format
    Given path '/accounts'
    And request
      """
      { email: '<email>' }
      """
    When method post
    Then status 400
    And match header api-version == '1.0.0'
    And match response == { error: '#string', description: '#string' }

    Examples:
      | email        |
      | not-an-email |
      | @example.com |
      | user@.com    |
