# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /aisp/account-consents/{consentId}_delete for http method type DELETE 
# RoostTestHash=460872f4ab
# 
# 

# ********RoostGPT********
Feature: Account Consent Deletion

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: Delete an Account Consent with valid consentId and headers
    Given url urlBase
    And path 'aisp/account-consents/', <consentId>
    And header x-fapi-auth-date = <x-fapi-auth-date>
    And header x-fapi-customer-ip-address = <x-fapi-customer-ip-address>
    And header x-fapi-interaction-id = <x-fapi-interaction-id>
    And header Accept-Language = <Accept-Language>
    When method delete
    Then status 204
    And match responseHeaders['x-fapi-interaction-id'] == <x-fapi-interaction-id>

    Examples:
      | read('aisp_account-consents_consentId_delete.csv') |

  Scenario: Delete an Account Consent with invalid consentId and expect 400 Bad Request
    Given url urlBase
    And path 'aisp/account-consents/', 'invalid-consent-id'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'unique-id-0002'
    And header Accept-Language = 'en-HK'
    When method delete
    Then status 400
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['x-fapi-interaction-id'] == 'unique-id-0002'
    And match response contains { errors: '#array' }

  Scenario: Delete an Account Consent without Authorization header and expect 401 Unauthorized
    Given url urlBase
    And path 'aisp/account-consents/', '7404e99b-1a4d-4b08-b441-c327661527f0'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'unique-id-0003'
    And header Accept-Language = 'en-HK'
    And removeHeader Authorization
    When method delete
    Then status 401

  Scenario: Delete an Account Consent with invalid Accept-Language and expect 406 Not Acceptable
    Given url urlBase
    And path 'aisp/account-consents/', '7404e99b-1a4d-4b08-b441-c327661527f0'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'unique-id-0004'
    And header Accept-Language = 'invalid-language'
    When method delete
    Then status 406
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['x-fapi-interaction-id'] == 'unique-id-0004'
    And match response contains { errors: '#array' }

  Scenario: Delete an Account Consent and expect 500 Internal Server Error
    Given url urlBase
    And path 'aisp/account-consents/', '7404e99b-1a4d-4b08-b441-c327661527f0'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'unique-id-0005'
    And header Accept-Language = 'en-HK'
    When method delete
    Then status 500
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['x-fapi-interaction-id'] == 'unique-id-0005'
    And match response contains { errors: '#array' }
