# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=6c81494c1a
# 
# 

# ********RoostGPT********
Feature: Account Consent Setup API Endpoints

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def consentId = '7404e99b-1a4d-4b08-b441-c327661527f0'
    * def headers =
      """
      {
        Authorization: 'Bearer ' + authToken,
        'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC',
        'x-fapi-customer-ip-address': '169.254.169.254',
        'x-fapi-interaction-id': 'interaction-id-12345',
        'Accept-Language': 'en-HK'
      }
      """

  Scenario: Retrieve Account Consent with Valid ConsentId
    Given path 'aisp/account-consents', consentId
    And headers headers
    When method GET
    Then status 200
    And match response contains { data: '#object', links: '#object' }
    And match response.data == { consentId: '#string', creationDate: '#string', status: '#string', statusUpdateDate: '#string', permissions: '#array' }
    And match response.links == { self: '#string' }

  Scenario: Retrieve Account Consent with Invalid ConsentId
    Given path 'aisp/account-consents', 'invalid-consent-id'
    And headers headers
    When method GET
    Then status 400
    And match response contains { errors: '#array' }

  Scenario: Retrieve Account Consent with Missing Authorization Header
    Given path 'aisp/account-consents', consentId
    And headers { 'x-fapi-auth-date': headers['x-fapi-auth-date'], 'x-fapi-customer-ip-address': headers['x-fapi-customer-ip-address'], 'x-fapi-interaction-id': headers['x-fapi-interaction-id'], 'Accept-Language': headers['Accept-Language'] }
    When method GET
    Then status 401

  Scenario: Retrieve Account Consent with Unsupported Method (POST)
    Given path 'aisp/account-consents', consentId
    And headers headers
    When method POST
    Then status 405

  Scenario: Retrieve Account Consent with Unsupported Accept-Language
    Given path 'aisp/account-consents', consentId
    And headers { Authorization: headers.Authorization, 'x-fapi-auth-date': headers['x-fapi-auth-date'], 'x-fapi-customer-ip-address': headers['x-fapi-customer-ip-address'], 'x-fapi-interaction-id': headers['x-fapi-interaction-id'], 'Accept-Language': 'unsupported-language' }
    When method GET
    Then status 406
