# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=6c81494c1a
# 
# 

# ********RoostGPT********
Feature: Account Consent Setup API Endpoints

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * header 'x-fapi-auth-date' = 'Sun, 10 Sep 2017 19:43:31 UTC'
    * header 'x-fapi-customer-ip-address' = '169.254.169.254'
    * header 'x-fapi-interaction-id' = 'unique-correlation-id'
    * header 'Accept-Language' = 'en-HK'

  Scenario Outline: Retrieve Account Consent with valid consentId and authorization
    Given url urlBase
    And path 'aisp/account-consents/', <consentId>
    When method get
    Then status 200
    And match response contains { data: '#object' }

    Examples:
      | consentId                              |
      | 7404e99b-1a4d-4b08-b441-c327661527f0   |

  Scenario: Retrieve Account Consent with invalid consentId
    Given url urlBase
    And path 'aisp/account-consents/', 'invalid-consent-id'
    When method get
    Then status 400
    And match response contains { errors: '#array' }

  Scenario: Retrieve Account Consent with missing authorization header
    Given url urlBase
    And path 'aisp/account-consents/', '7404e99b-1a4d-4b08-b441-c327661527f0'
    And header Authorization = ''
    When method get
    Then status 401

  Scenario: Retrieve Account Consent with unsupported method (POST)
    Given url urlBase
    And path 'aisp/account-consents/', '7404e99b-1a4d-4b08-b441-c327661527f0'
    And request {}
    When method post
    Then status 405

  Scenario: Retrieve Account Consent with valid consentId but service unavailable
    Given url urlBase
    And path 'aisp/account-consents/', '7404e99b-1a4d-4b08-b441-c327661527f0'
    When method get
    Then status 503

  Scenario: Retrieve Account Consent and validate response headers
    Given url urlBase
    And path 'aisp/account-consents/', '7404e99b-1a4d-4b08-b441-c327661527f0'
    When method get
    Then status 200
    And match responseHeaders contains { 'x-fapi-interaction-id': '#string' }
