# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=5a466edee9
# ROOST_METHOD_SIG_HASH=3ada4717c4
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Account Consent Setup',
#   background: 'Background:\r\n' +
#     "        * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')\r\n" +
#     '        * url urlBase\r\n' +
#     "        * def authToken = karate.properties['AUTH_TOKEN']",
#   rule: null,
#   scenario: {
#     title: 'Scenario Outline: Create account consent with valid data',
#     steps: "Given path '/aisp/account-consents'\r\n" +
#       "And header Authorization = 'Bearer ' + authToken\r\n" +
#       "And header Content-Type = 'application/json'\r\n" +
#       'And header x-fapi-auth-date = <x_fapi_auth_date>\r\n' +
#       'And header x-fapi-customer-ip-address = <x_fapi_customer_ip_address>\r\n' +
#       'And header x-fapi-interaction-id = <x_fapi_interaction_id>\r\n' +
#       'And header Accept-Language = <accept_language>\r\n' +
#       'And request <request_body>\r\n' +
#       'When method POST\r\n' +
#       'Then status 201\r\n' +
#       "And match responseHeaders['x-fapi-interaction-id'] == <x_fapi_interaction_id>\r\n" +
#       'And match response.data.consentId != null\r\n' +
#       'And match response.data.creationDate != null\r\n' +
#       "And match response.data.status == 'PendingAuthorise'\r\n" +
#       "And match response.data.permissions contains only ['ReadAccountAvailability', 'ReadAccountStatus', 'ReadAccountBalance', 'ReadAccountTransaction']\r\n" +
#       'And match response.data.expirationDate == <expiration_date>\r\n' +
#       'And match response.data.transactionFromDate == <transaction_from_date>\r\n' +
#       'And match response.data.transactionToDate == <transaction_to_date>\r',
#     examples: 'Examples:\r\n' +
#       '            | x_fapi_auth_date                | x_fapi_customer_ip_address | x_fapi_interaction_id | accept_language | request_body                                                                                                                                                                                | expiration_date        | transaction_from_date  | transaction_to_date    |\r\n' +
#       `            | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254'          | 'uniq-id-123'         | 'en-HK'         | { "data": { "permissions": ["ReadAccountBalance"], "expirationDate": "2023-12-31T23:59:59Z", "transactionFromDate": "2023-01-01T00:00:00Z", "transactionToDate": "2023-12-31T23:59:59Z" } } | '2023-12-31T23:59:59Z' | '2023-01-01T00:00:00Z' | '2023-12-31T23:59:59Z' |`
#   }
# }
# 

# ********RoostGPT********
Feature: Account Consent Setup

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Create account consent with valid data
    Given path '/aisp/account-consents'
    And header Authorization = 'Bearer ' + authToken
    And header Content-Type = 'application/json'
    And header x-fapi-auth-date = <x_fapi_auth_date>
    And header x-fapi-customer-ip-address = <x_fapi_customer_ip_address>
    And header x-fapi-interaction-id = <x_fapi_interaction_id>
    And header Accept-Language = <accept_language>
    And request <request_body>
    When method post
    Then status 201
    And match responseHeaders['x-fapi-interaction-id'] == <x_fapi_interaction_id>
    And match response.data.consentId != null
    And match response.data.creationDate != null
    And match response.data.status == 'PendingAuthorise'
    And match response.data.permissions contains only ['ReadAccountAvailability', 'ReadAccountStatus', 'ReadAccountBalance', 'ReadAccountTransaction']
    And match response.data.expirationDate == <expiration_date>
    And match response.data.transactionFromDate == <transaction_from_date>
    And match response.data.transactionToDate == <transaction_to_date>

    Examples:
      | x_fapi_auth_date                | x_fapi_customer_ip_address | x_fapi_interaction_id | accept_language | request_body                                                                                                                                                                                | expiration_date        | transaction_from_date  | transaction_to_date    |
      | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254'          | 'uniq-id-123'         | 'en-HK'         | """{ "data": { "permissions": ["ReadAccountBalance"], "expirationDate": "2023-12-31T23:59:59Z", "transactionFromDate": "2023-01-01T00:00:00Z", "transactionToDate": "2023-12-31T23:59:59Z" }}""" | '2023-12-31T23:59:59Z' | '2023-01-01T00:00:00Z' | '2023-12-31T23:59:59Z' |
