# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=ee0418c08a
# ROOST_METHOD_SIG_HASH=1c092be52c
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Diagnose and resolve WiFi interference issues',
#     steps: 'Given a customer with subscriber ID "SVTAL004" reports slow WiFi speeds\n' +
#       'When the support representative initiates a diagnostic test\n' +
#       'Then the service test API should return a test ID\n' +
#       'And the diagnostic result should indicate WiFi interference on the current channel\n' +
#       'When the support representative uses the configuration API to change the WiFi channel to an less congested one\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should report improved WiFi speeds',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

Background:
  * def serviceTestManagement_v2_URL = karate.properties['serviceTestManagement_v2_URL'] || karate.get('serviceTestManagement_v2_URL','http://localhost:4010')
  * def serviceActivationAndConfiguration_v1_URL = karate.properties['serviceActivationAndConfiguration_v1_URL'] || karate.get('serviceActivationAndConfiguration_v1_URL','http://localhost:4010')
  * def serviceTestManagement_v2_AUTH_TOKEN = karate.properties['serviceTestManagement_v2_AUTH_TOKEN'] || karate.get('serviceTestManagement_v2_AUTH_TOKEN','auth-token-placeholder')
  * def serviceActivationAndConfiguration_v1_AUTH_TOKEN = karate.properties['serviceActivationAndConfiguration_v1_AUTH_TOKEN'] || karate.get('serviceActivationAndConfiguration_v1_AUTH_TOKEN','auth-token-placeholder')

Scenario: Initiate diagnostic test for WiFi interference issues
  * url serviceTestManagement_v2_URL
  And header Authorization = 'Bearer ' + serviceTestManagement_v2_AUTH_TOKEN
  And def diagnosticPayload = 
    """
    {
      "serviceTest": {
        "type": "diagnostic",
        "customer": {
          "subscriberId": "SVTAL004"
        }
      }
    }
    """
  When method post
  Then status 200
  And assert response.control != null
  And assert response.control.type == 'S'
  And assert response.control.message != null
  And assert response.control.code != null
  And def testId = response.serviceTest
  And assert testId != null

Scenario: Change WiFi channel to resolve interference issues
  * url serviceActivationAndConfiguration_v1_URL
  And header Authorization = 'Bearer ' + serviceActivationAndConfiguration_v1_AUTH_TOKEN
  And def configurationPayload = 
    """
    {
      "configuration": {
        "action": {
          "type": "HGW_WIFI_CONFIGURATION",
          "parameters": {
            "newChannel": "6"
          }
        },
        "id": "config01",
        "adminStatus": "1",
        "startDate": "2023-04-01T08:00:00Z",
        "endDate": "2023-04-01T09:00:00Z",
        "state": "pending",
        "diagnostic": {}
      }
    }
    """
  When method post
  Then status 200
  And assert response.control != null
  And assert response.control.type == 'S'
  And assert response.control.message != null
  And assert response.control.code != null
  And assert response.configuration != null
  # Note: Verification of improved WiFi speeds is performed manually by customer feedback and is not part of this automated test
