# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=75c9169c0c
# ROOST_METHOD_SIG_HASH=7a25c565c6
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Diagnose and resolve weak WiFi signal',
#     steps: 'Given a customer with subscriber ID "SVTAL001" reports a weak WiFi signal\n' +
#       'When the support representative initiates a diagnostic test\n' +
#       'Then the service test API should return a test ID\n' +
#       'And the diagnostic result should indicate low WiFi signal strength\n' +
#       'When the support representative uses the configuration API to change the WiFi channel\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should report improved WiFi signal strength',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

Background:
  * def serviceTestManagementV2Url = karate.properties['SERVICETESTMANAGEMENT-V2_URL'] || karate.get('SERVICETESTMANAGEMENT-V2_URL', 'http://localhost:4010')
  * def serviceActivationAndConfigurationV1Url = karate.properties['SERVICEACTIVATIONANDCONFIGURATION-V1_URL'] || karate.get('SERVICEACTIVATIONANDCONFIGURATION-V1_URL', 'http://localhost:4010')

Scenario: Diagnose and resolve weak WiFi signal
  Given url serviceTestManagementV2Url
  And path '/serviceTest'
  And request 
    """
    {
      "serviceTest": {
        "type": "diagnostic",
        "customer": {
          "subscriberId": "SVTAL001"
        }
      }
    }
    """
  When method post
  Then status 200
  And match response.control != null
  And match response.control.type == '#regex[S|T|E]'
  And match response.control.message != null
  And match response.control.code != null
  And match response.serviceTest != null

  Given url serviceActivationAndConfigurationV1Url
  And path '/configuration'
  And request 
    """
    {
      "configuration": {
        "action": {
          "type": "HGW_WIFI_CONFIGURATION"
        },
        "id": "CFG001",
        "adminStatus": "1",
        "startDate": "2023-01-01T00:00:00Z",
        "endDate": "2023-01-02T00:00:00Z",
        "state": "active"
      }
    }
    """
  When method post
  Then status 200
  And match response.control != null
  And match response.control.type == '#regex[S|T|E]'
  And match response.control.message != null
  And match response.control.code != null
  And match response.configuration != null
