# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=ee0418c08a
# ROOST_METHOD_SIG_HASH=1c092be52c
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Diagnose and resolve WiFi interference issues',
#     steps: 'Given a customer with subscriber ID "SVTAL004" reports slow WiFi speeds\n' +
#       'When the support representative initiates a diagnostic test\n' +
#       'Then the service test API should return a test ID\n' +
#       'And the diagnostic result should indicate WiFi interference on the current channel\n' +
#       'When the support representative uses the configuration API to change the WiFi channel to an less congested one\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should report improved WiFi speeds',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

Background:
  * def serviceTestManagement_v2_ab6125f3b8_URL = karate.properties['SERVICETESTMANAGEMENT_V2_AB6125F3B8_URL'] || karate.get('SERVICETESTMANAGEMENT_V2_AB6125F3B8_URL', 'http://localhost:4010')
  * def serviceActivationAndConfiguration_v1_5d95612b48_URL = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_URL'] || karate.get('SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_URL', 'http://localhost:4010')
  * def serviceTestManagement_v2_ab6125f3b8_AUTH_TOKEN = karate.properties['SERVICETESTMANAGEMENT_V2_AB6125F3B8_AUTH_TOKEN'] || karate.get('SERVICETESTMANAGEMENT_V2_AB6125F3B8_AUTH_TOKEN', 'Bearer_Dummy_Token')
  * def serviceActivationAndConfiguration_v1_5d95612b48_AUTH_TOKEN = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_AUTH_TOKEN'] || karate.get('SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_AUTH_TOKEN', 'Bearer_Dummy_Token')

Scenario: Diagnose and resolve WiFi interference issues
  * url serviceTestManagement_v2_ab6125f3b8_URL
  And path '/serviceTest'
  And header Authorization = serviceTestManagement_v2_ab6125f3b8_AUTH_TOKEN
  And request
    """
    {
      "serviceTest": {
        "type": "diagnostic",
        "customer": {
          "subscriberId": "SVTAL004"
        }
      }
    }
    """
  When method post
  Then status 200
  And match response.control != null
  And match response.control.type == 'S' || response.control.type == 'T' || response.control.type == 'E'
  And match response.control.message != null
  And match response.control.code != null
  And def testId = response.serviceTest

  * url serviceActivationAndConfiguration_v1_5d95612b48_URL
  And path '/configuration'
  And header Authorization = serviceActivationAndConfiguration_v1_5d95612b48_AUTH_TOKEN
  And request
    """
    {
      "configuration": {
        "action": {
          "type": "HGW_WIFI_CONFIGURATION",
          "parameters": {
            "newChannel": "lessCongestedOne"
          }
        },
        "id": "#(testId)",
        "adminStatus": "1",
        "startDate": "2023-04-01T00:00:00Z",
        "endDate": "2023-04-01T01:00:00Z",
        "state": "pending",
        "diagnostic": {}
      }
    }
    """
  When method post
  Then status 200
  And match response.control != null
  And match response.control.type == 'S' || response.control.type == 'T' || response.control.type == 'E'
  And match response.control.message != null
  And match response.control.code != null
  And match response.configuration != null
