# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=a991089179
# ROOST_METHOD_SIG_HASH=5a667c5d20
# 
#  ########## Scenario ########## 
# 
# {
#   background: 'Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: 'Get Registration Details Of Recipient Person\r\n' +
#     '    Given id of recipient as 27364922937 in path parameter\r\n' +
#     '    And size=13 and offset=42 in request query\r\n' +
#     '    When the client sends a GET request to endpoint "/recipients/persons/{id}/registrations" \r\n' +
#     '    When authentication token is sent in request\r\n' +
#     '    Then for successful request having status code 200, Verify that headers have api-version, page-size and  page-offset\r\n' +
#     '    And response body must have element registrations and total.',
#   title: 'Get Registration Details Of Recipient Person'
# }
# 

# ********RoostGPT********
Feature: Get Registration Details Of Recipient Person

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:8080'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def recipientId = '27364922937'

  Scenario: Valid request to get registration details of a recipient person
    Given path 'recipients/persons/', recipientId, '/registrations'
    And param credential-url = null
    And param size = 13
    And param offset = 42
    And header Token = authToken
    When method get
    Then status 200
    And match header api-version == '1.0.0'
    And match header page-size == '13'
    And match header page-offset == '42'
    And match response == 
    """
    {
      total: '#number',
      registrations: [
        {
          id: '#uuid',
          reference: '#string',
          startDate: '#string',
          endDate: '#string',
          status: '#string',
          credentialUrl: '#string',
          suspendedUntil: '#string',
          issuedAt: '#string',
          createdAt: '#string',
          updatedAt: '#string'
        }
      ]
    }
    """

  Scenario: Unauthorized request to get registration details of a recipient person
    Given path 'recipients/persons/', recipientId, '/registrations'
    And param credential-url = null
    And param size = 13
    And param offset = 42
    And header Token = 'invalidToken'
    When method get
    Then status 401
    And match header api-version == '1.0.0'
    And match response == 
    """
    {
      error: '#string',
      description: '#string'
    }
    """
