# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=77709b3e66
# ROOST_METHOD_SIG_HASH=9efcbbb286
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Reset ONT device to resolve connectivity issues',
#     steps: 'Given a customer with subscriber ID "SVTAL002" reports intermittent internet connectivity\n' +
#       'When the support representative initiates a diagnostic test\n' +
#       'Then the service test API should return a test ID\n' +
#       'And the diagnostic result should indicate ONT connectivity issues\n' +
#       'When the support representative uses the configuration API to reset the GPON ONT\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should report stable internet connectivity',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

Background:
  * def serviceTestManagement_v2_ab6125f3b8_URL = karate.properties['SERVICETESTMANAGEMENT_V2_AB6125F3B8_URL'] || karate.get('SERVICETESTMANAGEMENT_V2_AB6125F3B8_URL', 'http://localhost:4010')
  * def serviceActivationAndConfiguration_v1_5d95612b48_URL = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_URL'] || karate.get('SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_URL', 'http://localhost:4010')
  * def serviceTestManagement_v2_ab6125f3b8_AUTH_TOKEN = karate.properties['SERVICETESTMANAGEMENT_V2_AB6125F3B8_AUTH_TOKEN'] || karate.get('SERVICETESTMANAGEMENT_V2_AB6125F3B8_AUTH_TOKEN', 'Bearer_Dummy_Token')
  * def serviceActivationAndConfiguration_v1_5d95612b48_AUTH_TOKEN = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_AUTH_TOKEN'] || karate.get('SERVICEACTIVATIONANDCONFIGURATION_V1_5D95612B48_AUTH_TOKEN', 'Bearer_Dummy_Token')

Scenario: Reset ONT device to resolve connectivity issues
  * url serviceTestManagement_v2_ab6125f3b8_URL
  And header Authorization = serviceTestManagement_v2_ab6125f3b8_AUTH_TOKEN
  And def diagnosticPayload = 
    """
    {
      "serviceTest": {
        "type": "diagnostic",
        "customer": {
          "subscriberId": "SVTAL002"
        }
      }
    }
    """
  And path '/serviceTest'
  And request diagnosticPayload
  When method post
  Then status 200
  And match response contains { control: '#object', serviceTest: '#notnull' }
  And match response.serviceTest.message == 'ONT connectivity issues'

  * url serviceActivationAndConfiguration_v1_5d95612b48_URL
  And header Authorization = serviceActivationAndConfiguration_v1_5d95612b48_AUTH_TOKEN
  And def resetPayload = 
    """
    {
      "configuration": {
        "action": {
          "type": "GPON_ONT_RESET"
        },
        "id": "some-config-id",
        "adminStatus": "1"
      }
    }
    """
  And path '/configuration'
  And request resetPayload
  When method post
  Then status 200
  And match response.control.type == 'S'

  * def customerFeedback = 'stable internet connectivity'
  And match customerFeedback == 'stable internet connectivity'
