# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=77709b3e66
# ROOST_METHOD_SIG_HASH=9efcbbb286
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Reset ONT device to resolve connectivity issues',
#     steps: 'Given a customer with subscriber ID "SVTAL002" reports intermittent internet connectivity\n' +
#       'When the support representative initiates a diagnostic test\n' +
#       'Then the service test API should return a test ID\n' +
#       'And the diagnostic result should indicate ONT connectivity issues\n' +
#       'When the support representative uses the configuration API to reset the GPON ONT\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should report stable internet connectivity',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

  Background:
    * def serviceTestManagement_v2_URL = karate.properties['serviceTestManagement_v2_URL'] || karate.get('serviceTestManagement_v2_URL','http://localhost:4010')
    * def serviceActivationAndConfiguration_v1_URL = karate.properties['serviceActivationAndConfiguration_v1_URL'] || karate.get('serviceActivationAndConfiguration_v1_URL','http://localhost:4010')
    * def serviceTestManagement_v2_AUTH_TOKEN = karate.properties['serviceTestManagement_v2_AUTH_TOKEN'] || karate.get('serviceTestManagement_v2_AUTH_TOKEN','auth_token_v2')
    * def serviceActivationAndConfiguration_v1_AUTH_TOKEN = karate.properties['serviceActivationAndConfiguration_v1_AUTH_TOKEN'] || karate.get('serviceActivationAndConfiguration_v1_AUTH_TOKEN','auth_token_v1')

  Scenario: Reset ONT device to resolve connectivity issues
    * url serviceTestManagement_v2_URL
    And path '/serviceTest'
    And header Authorization = 'Bearer ' + serviceTestManagement_v2_AUTH_TOKEN
    And request 
    """
    { 
      "serviceTest": { 
        "type": "diagnostic", 
        "customer": { 
          "subscriberId": "SVTAL002" 
        } 
      } 
    }
    """
    When method post
    Then status 200
    And match response contains 
    """
    { 
      "control": "#object", 
      "control.type": "S", 
      "control.message": "#string", 
      "control.code": "#string"
    }
    """
    And def testId = response.control.code

    * url serviceActivationAndConfiguration_v1_URL
    And path '/configuration'
    And header Authorization = 'Bearer ' + serviceActivationAndConfiguration_v1_AUTH_TOKEN
    And request 
    """
    { 
      "configuration": { 
        "action": { 
          "type": "GPON_ONT_RESET", 
          "parameters": {}
        },
        "customer": {}, 
        "id": "#string", 
        "adminStatus": "1", 
        "startDate": "#string", 
        "endDate": "#string", 
        "state": "#string", 
        "diagnostic": {}
      } 
    }
    """
    When method post
    Then status 200
    And match response contains 
    """
    { 
      "control": "#object", 
      "control.type": "S", 
      "control.message": "#string", 
      "control.code": "#string"
    }
    """
