# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=3252965470
# ROOST_METHOD_SIG_HASH=2a981df199
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Get Peer Stock Symbols and their corresponding Time Series values',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Given a stock symbol, get its peer stock symbols from finnhub.io, and for one of the peers, find their time series values from alphavantage.co',
#     steps: 'Given a stock symbol, get its peer stock symbols from finnhub.io, and for one of the peers, find their time series values from alphavantage.co\r\n' +
#       'Given a stock symbol "AAPL"\r\n' +
#       'And a request is hit to get its peer stock symbols from finnhub.io\r\n' +
#       'Then the request must be successful\r\n' +
#       'And the response should return an array of string\r\n' +
#       'When a request is made to fetch the time series values from alphavantage.co, of all the values obtained in previous response\r\n' +
#       'Then the request must be successful\r\n' +
#       'And the response should be valid',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Get Peer Stock Symbols and their corresponding Time Series values

Background:
  * def finnhub_URL = karate.properties['finnhub_URL'] ? karate.properties['finnhub_URL'] : 'http://localhost:4010'
  * def finnhub_AUTH_TOKEN = karate.properties['finnhub_AUTH_TOKEN'] ? karate.properties['finnhub_AUTH_TOKEN'] : 'c8b09fgad3i9edlcgrg0'

Scenario: Given a stock symbol, get its peer stock symbols from finnhub.io
  Given url finnhub_URL
  And param symbol = 'AAPL'
  And param token = finnhub_AUTH_TOKEN
  When method get
  Then status 200
  And match each response == '#string'
  # Expected outcome: An array of strings representing peer stock symbols is returned

Scenario: For one of the peers, find their time series values from finnhub.io
  Given url finnhub_URL
  And param symbol = 'MSFT' # Assuming 'MSFT' is one of the peers from the previous response
  And param resolution = 'D'
  And param from = 1572651390
  And param to = 1575243390
  And param token = finnhub_AUTH_TOKEN
  When method get
  Then status 200
  And match response.o contains only '#number'
  And match response.h contains only '#number'
  And match response.l contains only '#number'
  And match response.c contains only '#number'
  And match response.v contains only '#number'
  And match response.t contains only '#number'
  And match response.s == '#string'
  # Expected outcome: A valid response with time series data for the given peer stock symbol
