# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=6105ffde10
# ROOST_METHOD_SIG_HASH=e3af0b476f
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Troubleshoot and resolve a failed configuration change',
#     steps: 'Given a customer with subscriber ID "SVTAL006" requests a WiFi configuration change\n' +
#       'When the support representative uses the configuration API to make the requested change\n' +
#       'And the configuration API returns an error response\n' +
#       'Then the support representative should initiate a diagnostic test\n' +
#       'And the service test API should return a test ID\n' +
#       'And the diagnostic result should provide details about the configuration failure\n' +
#       'When the support representative resolves the identified issue and retries the configuration change\n' +
#       'Then the configuration API should return a success response\n' +
#       "And the customer's WiFi should reflect the requested changes",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

Background:
  * def serviceTestManagement_v2_URL = karate.properties['SERVICETESTMANAGEMENT_V2_URL'] || 'http://localhost:4010'
  * def serviceActivationAndConfiguration_v1_URL = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_URL'] || 'http://localhost:4010'
  * def serviceTestManagement_v2_AUTH_TOKEN = karate.properties['SERVICETESTMANAGEMENT_V2_AUTH_TOKEN'] || 'Bearer dummy_token'
  * def serviceActivationAndConfiguration_v1_AUTH_TOKEN = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_AUTH_TOKEN'] || 'Bearer dummy_token'

Scenario: Troubleshoot and resolve a failed configuration change
  * url serviceActivationAndConfiguration_v1_URL
  * path '/configuration'
  * header Authorization = serviceActivationAndConfiguration_v1_AUTH_TOKEN
  * def configurationRequestBody = 
  """
  {
    "configuration": {
      "action": {
        "type": "HGW_WIFI_CONFIGURATION"
      },
      "id": "SVTAL006",
      "adminStatus": "1",
      "startDate": "2023-01-01T00:00:00Z",
      "endDate": "2023-01-02T00:00:00Z",
      "state": "pending",
      "diagnostic": {}
    }
  }
  """
  Given request configurationRequestBody
  When method post
  Then status 400

  * url serviceTestManagement_v2_URL
  * path '/serviceTest'
  * header Authorization = serviceTestManagement_v2_AUTH_TOKEN
  * def diagnosticRequestBody = 
  """
  {
    "serviceTest": {
      "type": "diagnostic",
      "customer": {
        "subscriberId": "SVTAL006"
      }
    }
  }
  """
  Given request diagnosticRequestBody
  When method post
  Then status 200
  And match response contains { control: '#object' }
  And def testId = response.control.code

  * url serviceActivationAndConfiguration_v1_URL
  * path '/configuration'
  * header Authorization = serviceActivationAndConfiguration_v1_AUTH_TOKEN
  Given request configurationRequestBody
  When method post
  Then status 200
  And match response.control.type == 'S'
