# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=6105ffde10
# ROOST_METHOD_SIG_HASH=e3af0b476f
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Troubleshoot and resolve a failed configuration change',
#     steps: 'Given a customer with subscriber ID "SVTAL006" requests a WiFi configuration change\n' +
#       'When the support representative uses the configuration API to make the requested change\n' +
#       'And the configuration API returns an error response\n' +
#       'Then the support representative should initiate a diagnostic test\n' +
#       'And the service test API should return a test ID\n' +
#       'And the diagnostic result should provide details about the configuration failure\n' +
#       'When the support representative resolves the identified issue and retries the configuration change\n' +
#       'Then the configuration API should return a success response\n' +
#       "And the customer's WiFi should reflect the requested changes",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

Background:
  * def serviceTestManagementV2Url = karate.properties['SERVICETESTMANAGEMENT_V2_URL'] || 'http://localhost:4010'
  * def serviceActivationAndConfigurationV1Url = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_URL'] || 'http://localhost:4010'
  * def serviceTestManagementV2AuthToken = karate.properties['SERVICETESTMANAGEMENT_V2_AUTH_TOKEN'] || 'Bearer sometoken'
  * def serviceActivationAndConfigurationV1AuthToken = karate.properties['SERVICEACTIVATIONANDCONFIGURATION_V1_AUTH_TOKEN'] || 'Bearer sometoken'

Scenario: Troubleshoot and resolve a failed configuration change
  * url serviceActivationAndConfigurationV1Url
  * header Authorization = serviceActivationAndConfigurationV1AuthToken
  Given path '/configuration'
  And request """
    {
      "configuration": {
        "action": {
          "type": "HGW_WIFI_CONFIGURATION"
        },
        "customer": {},
        "id": "SVTAL006",
        "adminStatus": "1",
        "startDate": "2023-04-01T08:00:00Z",
        "endDate": "2023-04-01T09:00:00Z",
        "state": "pending",
        "diagnostic": {}
      }
    }
  """
  When method post
  Then status 400
  And match response == { type: 'E', message: '#string', code: '#string' }

  * url serviceTestManagementV2Url
  * header Authorization = serviceTestManagementV2AuthToken
  Given path '/serviceTest'
  And request """
    {
      "serviceTest": {
        "type": "diagnostic",
        "customer": {
          "subscriberId": "SVTAL006"
        }
      }
    }
  """
  When method post
  Then status 200
  And match response == { control: '#object', serviceTest: '#notnull' }

  * url serviceActivationAndConfigurationV1Url
  * header Authorization = serviceActivationAndConfigurationV1AuthToken
  Given path '/configuration'
  And request """
    {
      "configuration": {
        "action": {
          "type": "HGW_WIFI_CONFIGURATION"
        },
        "customer": {},
        "id": "SVTAL006",
        "adminStatus": "1",
        "startDate": "2023-04-01T10:00:00Z",
        "endDate": "2023-04-01T11:00:00Z",
        "state": "resolved",
        "diagnostic": {}
      }
    }
  """
  When method post
  Then status 200
  And match response == { control: '#object', configuration: '#notnull' }
