# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=5a02b01fca
# ROOST_METHOD_SIG_HASH=9c8324b0ac
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Update WiFi password for improved security',
#     steps: 'Given a customer with subscriber ID "SVTAL003" requests a WiFi password change\n' +
#       'When the support representative uses the configuration API to set a new WiFi password\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should be able to connect to the WiFi network with the new password',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

Background:
  * def serviceActivationAndConfiguration_v1_URL = karate.properties['serviceActivationAndConfiguration_v1_URL'] || karate.get('serviceActivationAndConfiguration_v1_URL','http://localhost:4010')
  * def serviceActivationAndConfiguration_v1_AUTH_TOKEN = karate.properties['serviceActivationAndConfiguration_v1_AUTH_TOKEN'] || karate.get('serviceActivationAndConfiguration_v1_AUTH_TOKEN','auth-token-placeholder')

Scenario: Update WiFi password for improved security
  * url serviceActivationAndConfiguration_v1_URL + '/configuration'
  And header Authorization = 'Bearer ' + serviceActivationAndConfiguration_v1_AUTH_TOKEN
  And request
  """
  {
    "configuration": {
      "action": {
        "type": "HGW_WIFI_SET_PASSWD",
        "parameters": {
          "subscriberId": "SVTAL003",
          "newPassword": "NewSecurePassw0rd"
        }
      },
      "customer": "SVTAL003",
      "id": "config-001",
      "adminStatus": "1",
      "startDate": "2023-04-01T00:00:00Z",
      "endDate": "2023-04-10T00:00:00Z",
      "state": "PENDING",
      "diagnostic": {}
    }
  }
  """
  When method post
  Then status 200
  And match response contains
  """
  {
    "control": {
      "type": "#string",
      "message": "#string",
      "code": "#string"
    }
  }
  """
