// Test generated by RoostGPT for test knote using AI Type Open AI and AI Model gpt-4

package com.learnk8s.knote;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class KnoteProperties_getUploadDir_caabfc00fd_Test {

    @Value("${upload.directory}")
    private String uploadDir;

    @MockBean
    private KnoteProperties knoteProperties;

    @BeforeEach
    public void setUp() {
        when(knoteProperties.getUploadDir()).thenReturn(uploadDir);
    }

    @Test
    public void testGetUploadDir_Success() {
        String expectedUploadDir = "/home/user/uploads";
        assertEquals(expectedUploadDir, knoteProperties.getUploadDir());
    }

    @Test
    public void testGetUploadDir_Failure() {
        String expectedUploadDir = "/home/user/wrong_dir";
        assertNotEquals(expectedUploadDir, knoteProperties.getUploadDir());
    }
}
