# ********RoostGPT********

# Test generated by RoostGPT for test multiple-gherkin-integration-test using AI Type Azure Open AI and AI Model Inference
# 
# ROOST_METHOD_HASH=80a99c245e
# ROOST_METHOD_SIG_HASH=a6412229b7
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credential Wallet API\\r","  As a user of the Credential Wallet API\\r","  I want to be able to perform CRUD operations on accounts\\r","  So that I can manage my account effectively\\r","\\r","',
#   background: 'Background:\\r","    Given the base URL is \\"http://localhost:8080\\"\\r","\\r","',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Create my account \\r","    When the client sends a POST request \\"/accounts\\" with the accounts_body payload\\r","    Then create an account with the specified informatio\\r","    And verify the account created using GET request for \\"/me\\"\\r","\\r","',
#     steps: 'When the client sends a POST request \\"/accounts\\" with the accounts_body payload\\r","    Then create an account with the specified informatio\\r","    And verify the account created using GET request for \\"/me\\"\\r","\\r","',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credential Wallet API
  As a user of the Credential Wallet API
  I want to be able to perform CRUD operations on accounts
  So that I can manage my account effectively

  Background:
    * url CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_URL = 'http://localhost:4010'
    * def AUTH_TOKEN = 'Bearer_Dummy_Token'

  Scenario: Create my account
    When the client sends a POST request "/accounts" with the accounts_body payload
    Then create an account with the specified information
    And verify the account created using GET request for "/me"
    * def payload = """
    {
      "email": "test@example.com"
    }
    """
    * url CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_URL
    * path '/accounts'
    * configure headers = {
      "commit-hash": "928d28d"
    }
    * request payload
    * method post
    * status 201
    * match response.headers contains {
      "api-version": "#string",
      "commit-hash": "#string"
    }
    # Verify the account created using GET request for "/me"
    * url CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_URL
    * path '/me'
    * configure headers = {
      Authorization: "#(karate.properties['AUTH_TOKEN'])"
    }
    * method get
    * status 200
    * match response contains {
      id: "#uuid",
      did: "#string?",
      name: "#string?",
      image: "#string?",
      email: "#email",
      settings: "#object",
      createdAt: "#date-time",
      updatedAt: "#date-time"
    }
    * match response.headers contains {
      "api-version": "#string"
    }
