// ********RoostGPT********
/*
Test generated by RoostGPT for test MiniProjects using AI Type  and AI Model 

ROOST_METHOD_HASH=92aa6a42f7
ROOST_METHOD_SIG_HASH=4d269fdf0c

 ########## Scenario ########## 

{
  feature: 'Feature: User and Address API integration',
  background: null,
  rule: null,
  scenario: {
    title: 'Scenario: Create a new User and their Address',
    steps: 'Given the API base URL is "https://api.example.com"\n' +
      'When I send a POST request to "/users" with the body:\n' +
      '      """\n' +
      '      {\n' +
      '        "name": "John Doe",\n' +
      '        "email": "john.doe@example.com"\n' +
      '      }\n' +
      'Then the response status code should be 201\n' +
      'And the response body should contain "userId"\n' +
      'When I send a POST request to "/users/{userId}/addresses" with the body:\n' +
      '      """\n' +
      '      {\n' +
      '        "street": "123 Main St",\n' +
      '        "city": "Somewhere",\n' +
      '        "state": "CA",\n' +
      '        "zip": "12345"\n' +
      '      }\n' +
      'Then the response status code should be 201\n' +
      'And the response body should contain "addressId"',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.learnk8s.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.util.HashMap;
import java.util.Map;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class CreateNewUserAndAddressTest {
    private static final String CSV_PATH = "src" + FileSystems.getDefault().getSeparator() +
            "test" + FileSystems.getDefault().getSeparator() +
            "java" + FileSystems.getDefault().getSeparator() +
            "com" + FileSystems.getDefault().getSeparator() +
            "learnk8s" + FileSystems.getDefault().getSeparator() +
            "RoostTest" + FileSystems.getDefault().getSeparator() +
            "CreateNewUserAndAddressTest.csv";
    private Map<String, String> testData;

    @BeforeEach
    public void setUp() throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader(CSV_PATH));
        String line;
        testData = new HashMap<>();
        reader.readLine(); // Skip headers
        while ((line = reader.readLine()) != null) {
            if (line.trim().isEmpty()) continue;
            String[] data = line.split("\\^\\|\\^");
            testData.put("Method", data[0]);
            testData.put("URL", data[1]);
            testData.put("REQ_HEADERS", data[2]);
            testData.put("REQ_BODY", data[3]);
            testData.put("RESPONSE_CODE", data[4]);
            testData.put("RESPONSE_BODY", data[5]);
        }
        reader.close();
    }

    @Test
    public void testCreateNewUser() {
        // Given the API base URL is "https://api.example.com"
        RestAssured.baseURI = "https://api.example.com";

        // When I send a POST request to "/users" with the body
        String createUserBody = testData.get("REQ_BODY");
        Response createUserResponse = given()
                .contentType(ContentType.JSON)
                .body(createUserBody)
                .when()
                .post(testData.get("URL"));

        // Then the response status code should be 201
        // And the response body should contain "userId"
        createUserResponse.then()
                .statusCode(Integer.parseInt(testData.get("RESPONSE_CODE")))
                .body("userId", not(empty()));

        String userId = createUserResponse.path("userId");

        // When I send a POST request to "/users/{userId}/addresses" with the body
        String createAddressBody = testData.get("REQ_BODY");
        Response createAddressResponse = given()
                .contentType(ContentType.JSON)
                .pathParam("userId", userId)
                .body(createAddressBody)
                .when()
                .post(testData.get("URL").replace("{userId}", userId));

        // Then the response status code should be 201
        // And the response body should contain "addressId"
        createAddressResponse.then()
                .statusCode(Integer.parseInt(testData.get("RESPONSE_CODE")))
                .body("addressId", not(empty()));
    }
}
