# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /accounts_post for http method type POST 
# RoostTestHash=53e96f9805
# 
# 

# ********RoostGPT********
Feature: Account Creation API Validation

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Create new Account with valid email
    Given path '/accounts'
    And header commit-hash = '<commit_hash>'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    And request
      """
      { 
        email: '<email>' 
      }
      """
    When method POST
    Then status 201
    And match header api-version == '1.0.0'
    And match header commit-hash == /^[a-z0-9]{7}$/

    Examples:
      | read('accounts_post.csv') |

  Scenario Outline: Create new Account with invalid email pattern
    Given path '/accounts'
    And header commit-hash = '<commit_hash>'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    And request
      """
      { 
        email: '<email>' 
      }
      """
    When method POST
    Then status 400
    And match header api-version == '1.0.0'
    And match response contains
      """
      { 
        error: '#string', 
        description: '#string' 
      }
      """
    And match response.error == /^validation/.*$/

    Examples:
      | email         | commit_hash |
      | 'test'        | '928d28d'   |
      | 'example.com' | '1a2b3c4'   |
