// ********RoostGPT********
/*
Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

Test generated for /rest/api/2/attachment/{id}_delete for http method type DELETE in rest-assured framework

RoostTestHash=b86ca8bb06


*/

// ********RoostGPT********
package io.learnk8s.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class attachmentIdDeleteTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src\test\java\io\learnk8s\RoostTest\attachment_idDeleteTest.csv");
    }

  
    @Test  
    public void attachmentIdDelete_Test() {
        this.setUp();
        for (Map<String, String> map : envList) {
          RestAssured.baseURI = map.get("BASE_URL");  
  
                Response response = given()
				.pathParam("id", map.get("id") != null ? map.get("id") : "")
				.header("Authorization", "Bearer " + map.get("AUTH_TOKEN"))
                .when()
                .delete("/rest/api/2/attachment/{id}")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 204) {
					System.out.println("Description: Returned if the request is successful.");
				}
if (response.statusCode() == 403) {
					System.out.println("Description: Returned if the user does not have the necessary permission.");
				}
if (response.statusCode() == 404) {
					System.out.println("Description: Returned if:

 *  the attachment is not found.
 *  attachments are disabled in the Jira settings.");
				}
  
            }  
    }
}
