// ********RoostGPT********
/*
Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=2cd54a0a81
ROOST_METHOD_SIG_HASH=809947a8ba

 ########## Scenario ########## 

{
  feature: 'Feature: Petstore E2E Flow\r\n' +
    '    As a user of the Petstore API\r\n' +
    '    I want to manage pets, orders, and user accounts\r\n' +
    '    So that I can run a successful pet store business',
  background: 'Background:\r\n' +
    '        Given the Petstore API is available at "https://petstore.swagger.io/v2"\r\n' +
    '        And I have valid API credentials\r\n' +
    '        And I am authenticated with OAuth2 token with "write:pets" and "read:pets" scopes',
  rule: null,
  scenario: {
    title: 'Scenario: Bulk operations',
    steps: 'Given I have multiple users to create\r\n' +
      'When I create users with array input\r\n' +
      '            | username  | email          | firstName | lastName |\r\n' +
      '            | bulkuser1 | bulk1@test.com | Bulk      | User1    |\r\n' +
      '            | bulkuser2 | bulk2@test.com | Bulk      | User2    |\r\n' +
      'Then all users should be created successfully\r\n' +
      'Given I have multiple pets to add\r\n' +
      'When I add the following pets:\r\n' +
      '            | name    | category | status    |\r\n' +
      '            | Max     | Dog      | available |\r\n' +
      '            | Charlie | Dog      | available |\r\n' +
      'Then all pets should be added successfully',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.learnk8s.integration_tests;

import io.restassured.http.ContentType;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import static io.restassured.RestAssured.given;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class BulkOperationsTest {
    private String payloadsPath;

    @BeforeEach
    public void setUp() {
        this.payloadsPath = Paths.get("src", "test", "java", "com", "learnk8s", "integration_tests", "BulkOperationsTest.csv")
                .toString();
    }

    @Test
    public void bulkOperationsTest() throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader(payloadsPath));
        String line = reader.readLine();  // Skip headers
        while((line = reader.readLine()) != null){
            if(line.isEmpty()){
                continue;
            }
            String[] payloadData = line.split("\\^\\|\\^");
            String method = payloadData[0], url = payloadData[1];
            JSONObject reqHeaders = new JSONObject(payloadData[2]), reqBody = new JSONObject(payloadData[3]), resBody = new JSONObject(payloadData[5]);
            String resCode = payloadData[4];

            // Assert status code and response body
            String response = given().headers(reqHeaders.toMap()).body(reqBody.toString())
                    .when().request(method, url)
                    .then().assertThat().statusCode(Integer.parseInt(resCode))
                    .extract().body().asString();

            // Assert entire response body
            assertEquals(response, resBody.toString());

            // Assert all properties in API spec
            JSONObject responseJson = new JSONObject(response);
            for (String key : resBody.keySet()) {
                assertEquals(resBody.get(key), responseJson.get(key));
            }
        }
        reader.close();
    }
}
