// ********RoostGPT********
/*
Test generated by RoostGPT for test multiple-gherkin-integration-test using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=80a99c245e
ROOST_METHOD_SIG_HASH=a6412229b7

 ########## Scenario ########## 

{
  feature: 'Feature: Credential Wallet API\\r","  As a user of the Credential Wallet API\\r","  I want to be able to perform CRUD operations on accounts\\r","  So that I can manage my account effectively\\r","\\r","',
  background: 'Background:\\r","    Given the base URL is \\"http://localhost:8080\\"\\r","\\r","',
  rule: null,
  scenario: {
    title: 'Scenario: Create my account \\r","    When the client sends a POST request \\"/accounts\\" with the accounts_body payload\\r","    Then create an account with the specified informatio\\r","    And verify the account created using GET request for \\"/me\\"\\r","\\r","',
    steps: 'When the client sends a POST request \\"/accounts\\" with the accounts_body payload\\r","    Then create an account with the specified informatio\\r","    And verify the account created using GET request for \\"/me\\"\\r","\\r","',
    examples: ''
  }
}

*/

// ********RoostGPT********
package com.learnk8s.integration_tests;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import static io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class CreateMyAccountTestTest {

    private List<String[]> payloadData;

    @BeforeEach
    public void setup() throws IOException {
        File payloadFile = new File("src" + File.separator + "test" + File.separator + "java" + File.separator + "com" + File.separator + "learnk8s" + File.separator + "integration_tests" + File.separator + "CreateMyAccountTestTest.csv");
        BufferedReader br = new BufferedReader(new FileReader(payloadFile));
        payloadData = br.lines().skip(1).map(line -> line.split("\\^\\|\\^")).toList();
        br.close();
    }

    @Test
    public void createMyAccountTest() {
        for (String[] payload : payloadData) {
            if (payload.length == 0) continue;

            String method = payload[0];
            String url = payload[1];
            String reqHeaders = payload[2];
            String reqBody = payload[3];
            int responseCode = Integer.parseInt(payload[4]);
            String responseBody = payload[5];

            if (method.equalsIgnoreCase("POST") && url.contains("/accounts")) {
                // Expected behavior: Create an account with the specified information
                Response response = RestAssured.given()
                        .header("Content-Type", ContentType.JSON)
                        .header("commit-hash", "COMMIT_HASH_EXAMPLE")
                        .body(reqBody)
                        .post(url);

                assertEquals(responseCode, response.getStatusCode(), "Status code should be " + responseCode);
                response.then().assertThat().body(matchesJsonSchemaInClasspath("schemas/create_account_response_schema.json"));
                response.then().assertThat().body("id", notNullValue())
                        .body("did", notNullValue())
                        .body("name", notNullValue())
                        .body("image", notNullValue())
                        .body("email", equalTo("example@example.com"))
                        .body("settings", notNullValue())
                        .body("createdAt", notNullValue())
                        .body("updatedAt", notNullValue());
            }

            if (method.equalsIgnoreCase("GET") && url.contains("/me")) {
                // Expected behavior: Verify the account created using GET request for "/me"
                Response response = RestAssured.given()
                        .header("Content-Type", ContentType.JSON)
                        .header("Token", "TOKEN_EXAMPLE")
                        .get(url);

                assertEquals(responseCode, response.getStatusCode(), "Status code should be " + responseCode);
                response.then().assertThat().body(matchesJsonSchemaInClasspath("schemas/get_account_response_schema.json"));
                response.then().assertThat().body("id", notNullValue())
                        .body("did", notNullValue())
                        .body("name", notNullValue())
                        .body("image", notNullValue())
                        .body("email", equalTo("example@example.com"))
                        .body("settings", notNullValue())
                        .body("createdAt", notNullValue())
                        .body("updatedAt", notNullValue());
            }
        }
    }
}
